run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
run
0
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:400:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
run
0
run
0
run
0
run
0
run
0
run
0
run
0
Error: "Failed to connect to socket: Connection refused (os error 111)"
run
0
Error: "Failed to connect to socket: Connection refused (os error 111)"
run
Error: "Failed to connect to socket: Connection refused (os error 111)"
1
Error: "Failed to connect to socket: Connection refused (os error 111)"
run
Error: "none of the requested outputs are valid"
1
run
Error: "There seems to already be another instance running..."
1
Error: "Socket file not found. Are you sure swww-daemon is running?"
run
WARNING: failed to load cache for output eDP-1: failed to open image: No such file or directory (os error 2)
0
run
WARNING: failed to load cache for output eDP-1: failed to open image: No such file or directory (os error 2)
0
run
WARNING: failed to load cache for output eDP-1: failed to open image: No such file or directory (os error 2)
0
